version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3
    container_name: pa195-spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./scripts:/scripts
      - ./volumes/spark/jars_dir:/opt/bitnami/spark/.ivy2:z
    ports:
      - '8080:8080'

  cassandra:
    image: bitnami/cassandra:3.11.10
    container_name: pa195-cassandra
    hostname: cassandra
    ports:
      - "9042:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./volumes/cassandra:/bitnami
      - ./scripts:/scripts
